export const ACHIEVMENTS = [
  {
    title: "Starstruck",
    description: "created a repository that has many stars",
    date: "2025-02-16",
    image: require("../assets/pack/starstruck.webp"),
    completed: true,
    color: "#873700",
  },
  {
    title: "Pull Shark",
    description: "opened a pull request that has been merged",
    date: "2023-09-20",
    image: require("../assets/pack/pull-shark.webp"),
    completed: true,
    color: "#001353",
  },
  {
    title: "Galaxy Brain",
    description: "answered a discussion with an accepted answer",
    date: "2023-10-05",
    image: require("../assets/pack/galaxy-brain.webp"),
    completed: true,
    color: "#240C7B",
  },
  {
    title: "Pair Extraordinaire",
    description: "coauthored commits on merged pull request",
    date: "2023-11-12",
    image: require("../assets/pack/pair-extraordinaire.webp"),
    completed: true,
    color: "#065100",
  },
  {
    title: "YOLO",
    description: "You want it? You merge it.",
    date: "2023-12-01",
    image: require("../assets/pack/yolo.webp"),
    completed: true,
    color: "#2C3389",
  },
  {
    title: "Quickdraw",
    description: "Gitty up!",
    image: require("../assets/pack/quickdraw.webp"),
    completed: false,
    color: "#902900",
  },
  {
    title: "Public Sponsor",
    description: "Sponsored an open source contributor through GitHub Sponsors",
    image: require("../assets/pack/public-sponsor.webp"),
    completed: false,
    color: "#8C225E",
  },
  {
    title: "Arctic Code Vault Contributor",
    description:
      "Contributed code to repositories in the 2020 GitHub Archive Program",
    image: require("../assets/pack/arctic-code-vault-contributor.webp"),
    completed: false,
    color: "#001171",
  },
];
